name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        stage: [unstable, testing, release-3_0, release-3_1]
        os:
          - distro: debian
            codename: bullseye
          - distro: debian
            codename: bookworm
          - distro: debian
            codename: testing

          - distro: ubuntu
            codename: focal
          - distro: ubuntu
            codename: jammy
          - distro: ubuntu
            codename: mantic
          - distro: ubuntu
            codename: noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{ matrix.os.distro }} ${{ matrix.os.codename }} ${{ matrix.stage }}
        uses: ./${{ matrix.os.distro }}/${{ matrix.os.codename }}
        with:
          apt-key-url: http://regolith-desktop.org/regolith3.key
          apt-repo-line: "deb [arch=amd64] https://regolith-desktop.org/${{ matrix.stage }}-${{ matrix.distro }}-${{ matrix.codename }}-amd64 ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
